### ISSUE TITLE
pypi with latest version ?

### ISSUE THREAD

**Issue by AntonioReyes** [maccesch/cmsplugin-contact#57]
Hi 
is the pypi with the latest version of the code ?

I've managed to install it from zip in my local machine with your latest "from email changes " but I can't do the same on my heroku app.

Do you have any idea how I can install it manually on heroku or are planning to update the pypi soon ?

Thanks,

**Comment by saeedsq** [comment]
Version 1.1.1 could not be installed using pip
Could not find a version that satisfies the requirement cmsplugin-contact==1.1.1 (from versions: 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 1.0.0, 1.1.0)
No matching distribution found for cmsplugin-contact==1.1.1
