### ISSUE TITLE
 form ContactAdminForm needs updating (RemovedInDjango18Warning)

### ISSUE THREAD

**Issue by saeedsq** [maccesch/cmsplugin-contact#78]
C:\Python27\lib\site-packages\cmsplugin_contact-1.1.1-py2.7.egg\cmsplugin_contact\admin.py:15: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or th
e 'exclude' attribute is deprecated - form ContactAdminForm needs updating
  class ContactAdminForm(ModelForm):

**Comment by saeedsq** [comment]
This repo is inactive. No one is responding to issues

**Comment by maccesch** [comment]
No, it's still active, just don't have the time right now. If you post a pull request it will be merged though.
