### ISSUE TITLE
"Your models have changes that are not yet reflected in a migration, and so won't be applied."

### ISSUE THREAD

**Issue by mjtorn** [maccesch/cmsplugin-contact#84]
Django told me the models aren't in sync, please take a look at this

```
$ python manage.py makemigrations --dry-run
```

> Migrations for 'cmsplugin_contact':
>   0002_auto_20160225_1709.py:
>     - Alter field form_layout on contact
>     - Alter field recaptcha_theme on contact
>     - Alter field site_email on contact
>     - Alter field spam_protection_method on contact

Thanks!

**Comment by maccesch** [comment]
I'm afraid I won't have time in the near future to fix anything. I'd appreciate a pull request though!
