### ISSUE TITLE
Continuous loading when adding contact form.

### ISSUE THREAD

**Issue by LukeNisbet** [maccesch/cmsplugin-contact#91]
When adding the contact form to a page using the structure mode of the GUI, the spinner will continue indefinitely. Can anyone help I have installed as per the instructions on the page.  

![image](https://cloud.githubusercontent.com/assets/22999481/23772084/94dd1b1e-0511-11e7-93b6-576d2df3998f.png)

**Comment by vaskinyy** [comment]
same here. I use the latest django cms

**Comment by JurajKavka** [comment]
and same here :D after the hitting save button, no request is fired to server. 

```
django-cms==3.4.4 
cmsplugin-contact==1.1.2
```

**Comment by maccesch** [comment]
I just uploaded the latest version to PyPI. Does this bug still persist?

**Comment by fsbraun** [comment]
Still have the issue with ``cmsplugin-contact==1.1.3`` and ``django-cms==3.4.4``. I have no clue where the system gets stuck.

**Comment by maccesch** [comment]
Unfortunately I don't have time to investigate. I will accept pull requests though.

**Comment by okfish** [comment]
Just rename model field `submit` to smth like `submit_text` and that's all. I think Django-CMS `cms.modal.js` does not like that naming but I can't understand why it happens
